apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: helm-exporter
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: helm-exporter
    helm.sh/chart: helm-exporter-0.3.1
  name: helm-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: helm-exporter
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: helm-exporter
    helm.sh/chart: helm-exporter-0.3.1
  name: helm-exporter
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9571
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: helm-exporter
    app.kubernetes.io/name: helm-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: helm-exporter
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: helm-exporter
    helm.sh/chart: helm-exporter-0.3.1
  name: helm-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: helm-exporter
      app.kubernetes.io/name: helm-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: helm-exporter
        app.kubernetes.io/name: helm-exporter
    spec:
      containers:
      - image: sstarcher/helm-exporter:0.4.2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: helm-exporter
        ports:
        - containerPort: 9571
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccountName: helm-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: helm-exporter
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: helm-exporter
    helm.sh/chart: helm-exporter-0.3.1
  name: helm-exporter
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: helm-exporter
      app.kubernetes.io/name: helm-exporter
