apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compactor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos-compactor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-compactor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-compactor
      annotations:
        iam.amazonaws.com/role: ThanosRole
    spec:
      containers:
        - name: thanos-compactor
          image: quay.io/thanos/thanos:v0.8.1
          args:
            - compact
            - --log.level=debug
            - --data-dir=/var/thanos/store
            - --objstore.config=$(OBJSTORE_CONFIG)
            - --http-address=0.0.0.0:9090
            - --retention.resolution-raw=14d
            - --retention.resolution-5m=30d
            - --retention.resolution-1h=60d
            - --block-sync-concurrency=5
            - --wait
          env:
            - name: OBJSTORE_CONFIG
              valueFrom:
                secretKeyRef:
                  key: thanos.yaml
                  name: thanos-objstore-config
          ports:
            - containerPort: 9090
              name: http
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
          volumeMounts:
            - name: data
              mountPath: /var/thanos/store
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
      volumes:
        - name: data
          emptyDir: {}
      